### ISSUE TITLE
AssertionError: [ 0.56517062 -0.18227784] is an invalid action

### ISSUE THREAD

**Issue by Vulpes25** [vinerya/dynamic_soaring_rl#1]
Hi Vinerya,

Greetings! Thank you for your work! I am currently focusing on dynamic soaring reinforcement learning, and I find your research to be very helpful. However, I am a noob in Python, and I encountered an error while running your code: "AssertionError: [0.56517062 -0.18227784] is an invalid action. I attempted to resolve the issue, but I noticed that the action range is from -1 to 1, which includes the value [0.56517062 -0.18227784]. Can you tell me how to fix this? Thank you!

Best wishes,
Vulpes

**Comment by Vulpes25** [comment]
By adding this code after line 23:
       "action = action.astype(np.float32)"
This problem is solved. Thank you again with this nice work.

**Comment by vinerya** [comment]
thanks for pointing this issue and also finding the fix. I will update it asap.
